server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location = /socials/spotify {
        return 301 https://open.spotify.com/artist/51aizcUAA7QuxTN9KBQcT1;
    }

    location = /socials/youtube {
        return 301 https://www.youtube.com/@rgxgarca;
    }

    location = /socials/ytmusic {
        return 301 https://music.youtube.com/@rgxgarca;
    }

    location = /socials/instagram {
        return 301 https://www.instagram.com/rg_x_garca/;
    }

    location = /socials/tiktok {
        return 301 https://www.tiktok.com/@rg_x_garca;
    }
}